config/routes.rb
Rails.application.routes.draw do
  get 'todos/list', to: 'todos#list'
  resources :todos
  get 'todos/:id/complete', to: 'todos#complete', as: 'complete'
  # get 'todos', to: 'todos#index'
  # get 'todos/new'
  # post 'todos', to: 'todos#create'
  # get 'todos/:id', to: 'todos#show', as: 'todo'
  # get 'todos/:id/edit', to: 'todos#edit', as: 'edit'
  # patch 'todos/:id', to: 'todos#update'
  # delete 'todos/:id', to: 'todos#destroy'
  #
  root 'todos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :find_todo, only: [:show, :edit, :update, :destroy, :complete]


  def index
    @todos = Todo.all
  end
  
  def list
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todos_params)
    @todo.save
    redirect_to todos_path
  end

  def show
  end

  def edit
  end

  def update
    @todo.update(todos_params)
    redirect_to root_path
  end

  def destroy
    @todo.destroy
    redirect_to root_path
  end

  def complete
    @todo.update(completed: true)
    @todo.save
    redirect_to root_path
  end


  private
  def todos_params
    params.require(:todo).permit(:description, :completed)
  end

  def find_todo
    @todo = Todo.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with model: @todo, local: true do |form| %>
<form>

  <div class="form-group">

    <label>  <%= form.label :description, "Detalle de la tarea" %> </label>
    <input placeholder="detalle" <%= form.text_area :description %>  </input>
  </div>

  <div class="form-group">
    <label>  <%= form.label :completed, "Completado?" %> </label>
    <input  <%= form.check_box :completed %> </input>
  </div>

  <div class="form-group">
    <input class="btn btn-lg btn-primary" type="submit" <%= form.submit "Crear" %>
  </div>

</div>
</div>
</form>
<% end %>

app/views/todos/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">ToDOiX</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if params[:action]=='index'  %>"><a href="<%= todos_path %>">Index</a></li>
        <li class="<%= 'active' if params[:action]=='list' %>"><a href="<%= todos_list_path %>">List</a></li>
        <li class="<%= 'active' if params[:action]=='new' %>"><a href="<%= new_todo_path %>">Nuevo</a></li>

      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/todos/edit.html.erb
<%= render 'navbar' %>
<div class="container" style="padding: 50px;">
  <h1>Editar <small>Tarea</small></h1>
  <%= render 'form' %>
  <div class="container">
    <p>
      <%= link_to 'Mostrar', @todo %> |
      <%= link_to 'Atrás', todos_path %>
    </p>
  </div>
</div>

app/views/todos/index.html.erb
<%= render 'navbar' %>
<div class="container" style="padding: 50px;">
<h1><%= link_to "Crear Nuevo", new_todo_path %></h1>

  <% @todos.each do |todo| %>
    <div class="well">
      <h3> <%= link_to todo.description, todo %> </h3>
      <p> <%= todo.completed %> </p>
      <p><%= link_to 'Editar', edit_todo_path(todo) %> |
      <%= link_to "Completado", complete_path(todo) %> |
      <%= link_to "Borrar", todo, method: :delete, data: { confirm: '¿Estás Seguro?' } %>

      </p>
    </div>
  <% end %>
</div>

app/views/todos/list.html.erb
<%= render 'navbar' %>
<div class="container" style="padding: 50px;">

  <div class="row">
    <div class="col-md-6">
      <h1>Done</h1>


    <% @todos.each do |todo| %>
        <% if todo.completed %>
        <div class="well">
          <h3><s> <%= link_to todo.description, todo %> </s></h3>
          <p> <%= todo.completed %> </p>
          <p><%= link_to 'Editar', edit_todo_path(todo) %> |
          <%= link_to "Borrar", todo, method: :delete, data: { confirm: '¿Estás Seguro?' } %>
          </p>
        </div>
        <% end %>
    <% end %>

  </div>

  <div class="col-md-6">
    <h1>2Do</h1>
    <% @todos.each do |todo| %>
        <% if !todo.completed %>
        <div class="well">
          <h3> <%= link_to todo.description, todo %> </h3>
          <p> <%= todo.completed %> </p>
          <p><%= link_to 'Editar', edit_todo_path(todo) %> |
          <%= link_to "Completado", complete_path(todo) %> |
          <%= link_to "Borrar", todo, method: :delete, data: { confirm: '¿Estás Seguro?' } %>
          </p>
        </div>
        <% end %>
    <% end %>

  </div>


</div>



</div>

app/views/todos/new.html.erb
<%= render 'navbar' %>
<div class="container" style="padding: 50px;">
  <h1>Nueva <small>Tarea</small></h1>
  <%= render 'form' %>
</div>

app/views/todos/show.html.erb
<%= render 'navbar' %>
<div class="container" style="padding: 50px;">
  <div class="well">

    <h1> <%= @todo.description %>  </h1>
    <p> <%= @todo.completed %> </p>
    <p> Creado hace acerca de: <%= time_ago_in_words @todo.created_at %> </p>
    <%= link_to "editar", edit_todo_path %>
  </div>
</div>